### ISSUE TITLE
BSEQuencer

### ISSUE THREAD

**Issue by fpesari** [geekosdawproject/geekosdaw-issues#11]
**Category**: Plugin (LV2)
**Description**: MIDI step sequencer
**License**: GPLv3
**Web page or repository**: https://github.com/sjaehn/BSEQuencer

**Comment by KottV** [comment]
A brief package has been made: https://build.opensuse.org/package/show/home:kill_it/BSEQuencer
no changelog, no upstream patches

**Comment by fpesari** [comment]
For packaging updates from now on we are going to adhere to [this](https://en.opensuse.org/openSUSE:Package_naming_guidelines#SCM_snapshots), instead of using separate patches.

**Comment by KottV** [comment]
What is a "packaging updates"? :)
Some time before You said that packaging policy is the _release_+important patches.
Don't get me wrong, I prefer stay on upstream's bleeding edge and test it during development - regarding synth/plugins. While underling libraries (such JUCE or LV2) should be well tested and include critical fixes if necessary.

**Comment by fpesari** [comment]
> What is a "packaging updates"? :)
> Some time before You said that packaging policy is the _release_+important patches.
> Don't get me wrong, I prefer stay on upstream's bleeding edge and test it during development - regarding synth/plugins. While underling libraries (such JUCE or LV2) should be well tested and include critical fixes if necessary.

I studied official Factory packages a bit more and it seems that they allow this kind of versioning, so we could use it to make packages which are easier to maintain (since patches are kinda annoying).

**Comment by fpesari** [comment]
@KottV did the package. Closing.
