### ISSUE TITLE
Camomile

### ISSUE THREAD

**Issue by fpesari** [geekosdawproject/geekosdaw-issues#19]
**Category**: Plugin (LV2)
**Description**: Embed Pure Data as a LV2 plugin
**License**: GPLv3
**Web page or repository**: https://github.com/pierreguillot/Camomile

**Comment by KottV** [comment]
Camomile has been build very well.
What we have to decide is where it should be installed? There is no "make install" methods in original source and concept is straightforward:
Camomile has simple bash script which must be executed in same dir with plugins prototypes: https://github.com/pierreguillot/Camomile/wiki/How-to-generate-plugins

So no link to /usr/bin/ ether simple call /somewheretocamomiledir/camomile "$@" will work.
I suppose to put Camomile dir with its script in /usr/lib64/Camomile
add README.SUSE file with simple instruction and URL to wiki

What do you think?

**Comment by fpesari** [comment]
Yes, I made the package in my own home: right now, and I experienced some of those issues.

You had a very good idea, however perhaps I will try submitting a patch upstream to allow proper usage of system-wide paths (/usr/bin and /usr/lib or /usr/lib64), what do you think?

**Comment by KottV** [comment]
well, if we want to put package quickly - we can take my "solution"
but lets try to make a new script and pull it in upstream

**Comment by fpesari** [comment]
Done
