### ISSUE TITLE
Unnecessary re-downloads

### ISSUE THREAD

**Issue by thoth-amon** [geekosdawproject/geekosdaw-issues#79]
When I update, I get lots of downloads of packages that haven't been updated actually but have some minute version increment. For example the package 6pm that hasn't been updated for years wants to re-download

> 6pm                                0.9-1.81 -> 0.9-1.82

and this is the case with many, some more examples..

>  lv2-BAngr                          1.6.0-1.71 -> 1.6.0-1.72
>   lv2-BChoppr                        1.12.6-1.47 -> 1.12.6-1.48
>   lv2-BJumblr                        1.6.8-2.73 -> 1.6.8-2.74
>   lv2-BOops                          1.8.2-1.59 -> 1.8.2-1.60
>   lv2-BSchaffl                       1.4.10-1.67 -> 1.4.10-1.68
>   lv2-BSEQuencer                     1.8.10-1.72 -> 1.8.10-1.73

It causes regular large update sizes.

Why is this happening? Have I something wrongly configured?

**Comment by KottV** [comment]
This happens when some of the dependencies was updated. For example: https://build.opensuse.org/packages/6pm/build_reason/multimedia:proaudio/openSUSE_Tumbleweed/x86_64
