### ISSUE TITLE
Ray Session needs update?

### ISSUE THREAD

**Issue by thoth-amon** [geekosdawproject/geekosdaw-issues#80]
It's not opening and giving an error of 

```
Traceback (most recent call last):
  File "/usr/share/raysession/src/bin/raysession", line 13, in <module>
    from gui_tools import ArgParser, CommandLineArgs, init_gui_tools, get_code_root
  File "/usr/share/raysession/src/gui/gui_tools.py", line 9, in <module>
    from liblo import Address
```

which may be related to this https://github.com/Houston4444/RaySession/pull/234

which was fixed in this https://github.com/Houston4444/RaySession/releases/tag/v0.14.4

**openSUSE Version**: Tumbleweed

**Comment by KottV** [comment]
Thanks, updated.
