### ISSUE TITLE
Carla not starting

### ISSUE THREAD

**Issue by thoth-amon** [geekosdawproject/geekosdaw-issues#81]
**Bug description**:

Get this terminal output when I try to load it

> Traceback (most recent call last):
>   File "/usr/share/carla/carla", line 8, in <module>
>     from carla_app import (
>   File "/usr/share/carla/carla_app.py", line 19, in <module>
>     from qt_compat import qt_config
>   File "/usr/share/carla/qt_compat.py", line 14, in <module>
>     from PyQt6.QtCore import Qt, QEvent, QEventLoop
> ModuleNotFoundError: No module named 'PyQt6'

**openSUSE Version**: Tumbleweed

**Comment by KottV** [comment]
does it work if you install PyQt6?
`sudo zypper in python311-PyQt6`

**Comment by thoth-amon** [comment]
I had python313-PyQt6 installed. It still doesn't work but I now get a different error message

> Carla 2.6.0-alpha1 started, status:
>   Python version: 3.11.11
>   Qt version:     6.8.1
>   PyQt version:   6.8.0.dev2410061818
>   Binary dir:     /usr/lib64/carla
>   Resources dir:  /usr/share/carla/resources
> Traceback (most recent call last):
>   File "/usr/share/carla/carla", line 53, in <module>
>     gui = HostWindow(host, True)
>           ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/share/carla/carla_host.py", line 490, in __init__
>     self.ui.glView = QGLWidget(self)
>                      ^^^^^^^^^^^^^^^
> TypeError: arguments did not match any overloaded call:
>   QGLWidget(parent: Optional[QWidget] = None, shareWidget: Optional[QGLWidget] = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'HostWindow'
>   QGLWidget(context: Optional[QGLContext], parent: Optional[QWidget] = None, shareWidget: Optional[QGLWidget] = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'HostWindow'
>   QGLWidget(format: QGLFormat, parent: Optional[QWidget] = None, shareWidget: Optional[QGLWidget] = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'HostWindow'

**Comment by KottV** [comment]
Carla requires python-3.11, so you need this version exact `python311-PyQt6`

**Comment by thoth-amon** [comment]
Sorry, my last post wasn't clear. I have python311-PyQt6 installed now. I get the following error message

> Carla 2.6.0-alpha1 started, status:
> Python version: 3.11.11
> Qt version: 6.8.1
> PyQt version: 6.8.0.dev2410061818
> Binary dir: /usr/lib64/carla
> Resources dir: /usr/share/carla/resources
> Traceback (most recent call last):
> File "/usr/share/carla/carla", line 53, in
> gui = HostWindow(host, True)
> ^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/share/carla/carla_host.py", line 490, in init
> self.ui.glView = QGLWidget(self)
> ^^^^^^^^^^^^^^^
> TypeError: arguments did not match any overloaded call:
> QGLWidget(parent: Optional[QWidget] = None, shareWidget: Optional[QGLWidget] = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'HostWindow'
> QGLWidget(context: Optional[QGLContext], parent: Optional[QWidget] = None, shareWidget: Optional[QGLWidget] = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'HostWindow'
> QGLWidget(format: QGLFormat, parent: Optional[QWidget] = None, shareWidget: Optional[QGLWidget] = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'HostWindow'

**Comment by thoth-amon** [comment]
Ahh, the problem was OpenGL rendering doesn't work, so I needed to turn that option off.
