### ISSUE TITLE
wolf-shaper

### ISSUE THREAD

**Issue by fpesari** [geekosdawproject/geekosdaw-issues#9]
**Category**: Plugin (LV2)
**Description**: Waveshaper plugin
**License**: GPLv3
**Web page or repository**: https://github.com/pdesaulniers/wolf-shaper

**Comment by fpesari** [comment]
[Done](https://build.opensuse.org/package/show/home:geekositalia:daw/wolf-shaper). But there are some patches from git to implement, so I'll keep this issue open.

**Comment by KottV** [comment]
> 
> 
> [Done](https://build.opensuse.org/package/show/home:geekositalia:daw/wolf-shaper). But there are some patches from git to implement, so I'll keep this issue open.

we can do it in two ways:
1. pull from git and pack with +gitNNNNN prefix
2. add commits as the patches in sources

**Comment by fpesari** [comment]
2) would be better, if you can do it please, do and add it to the changelog :smile_cat:

**Comment by KottV** [comment]
[Done](https://build.opensuse.org/request/show/738132)

**Comment by KottV** [comment]
>     1. would be better, if you can do it please, do and add it to the changelog smile_cat

All commits or particular ones? If the all, then there is no differences between both ways.
Damn, as you can see there was "1" in your original reply, or not? :)

**Comment by fpesari** [comment]
Done, closing.
